export const ADD_LINK_SUCCESS = 'ADD_LINK_SUCCESS'
export const ADD_LINK_ERROR = 'ADD_LINK_ERROR'
export const GET_PROJECT_SUCCESS = 'GET_PROJECT_SUCCESS'
export const GET_PROJECT_ERROR = 'GET_PROJECT_ERROR'