export const GET_LINK_SUCCESS = 'GET_LINK_SUCCESS'
export const GET_LINK_ERROR = 'GET_LINK_ERROR'
export const DELETE_LINK_SUCCESS = 'DELETE_LINK_SUCCESS'
export const DELETE_LINK_ERROR = 'DELETE_LINK_ERROR'